import { type BallisticWeapon, ITEM_TYPES, type ItemsVolume } from "./types.ts";

export const BallisticItems: ItemsVolume<BallisticWeapon> = {
  common: {
    m5_assault_rifle: {
      id: "m5_assault_rifle",
      name: "M5 Assault Rifle",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "Standard-issue. Every soldier knows how to use one.",
      usable: true,
      icon: "weapon_57.png",
      quantity: 1,
      damage: 12,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 6,
    },
    hunting_rifle: {
      id: "hunting_rifle",
      name: "Old Hunting Rifle",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "Familiar to anyone who's spent time in the bush.",
      usable: true,
      icon: "weapon_53.png",
      quantity: 1,
      damage: 13,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 2,
      restrictRole: "rifleman",
    },
    damaged_war_rifle: {
      id: "damaged_war_rifle",
      name: "Old War Rifle",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "This baby has seen some action.",
      usable: true,
      icon: "weapon_39.png",
      quantity: 1,
      damage: 11,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 3,
      restrictRole: "rifleman",
    },
    m240_delta_machine_gun: {
      // MG support
      id: "m240_delta_machine_gun",
      name: "M240 Delta Pattern Machine Gun",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "The backbone of many a fire team.",
      usable: true,
      icon: "weapon_45.png",
      quantity: 1,
      damage: 35,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 7,
      restrictRole: "support",
    },
    s44_galt: {
      id: "s44_galt",
      name: "S44 Galt Carbine",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "Developed in former Belgium, a staple for light infantry.",
      usable: true,
      icon: "weapon_29.png",
      quantity: 1,
      damage: 11,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 7,
      restrictRole: "rifleman",
    },
    m16_a6_assault_rifle: {
      id: "m16_a6_assault_rifle",
      name: "M16 A6",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "A battle-tested classic. Still gets the job done.",
      usable: true,
      icon: "weapon_23.png",
      quantity: 1,
      damage: 13,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 6,
      restrictRole: "rifleman",
    },
    double_barrel_shotgun: {
      id: "double_barrel_shotgun",
      name: "Double barrel shotgun",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description:
        "Not very practical on the modern battlefield, but it packs a punch!",
      usable: true,
      icon: "weapon_43.png",
      quantity: 1,
      damage: 14,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 1,
      restrictRole: "rifleman",
    },
    m201_automatic_shotgun: {
      id: "m201_automatic_shotgun",
      name: "M201 Automatic Shotgun",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "Developed for law enforcement. Favored in close quarters.",
      usable: true,
      icon: "weapon_28.png",
      quantity: 1,
      damage: 24,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 4,
      restrictRole: "rifleman",
    },
    lsaw_guardsman: {
      id: "lsaw_guardsman",
      name: "LSAW Guardsman Rifle",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "A counter-sniper's tool of choice.",
      usable: true,
      icon: "weapon_34.png",
      quantity: 1,
      damage: 35,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 2,
      restrictRole: "rifleman",
    },
    akpd_assault_rifle: {
      id: "akpd_assault_rifle",
      name: "AK PD-2 Assault Rifle",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "Based on the venerable AK-47 lineage.",
      usable: true,
      icon: "weapon_14.png",
      quantity: 1,
      damage: 10,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 8,
      restrictRole: "rifleman",
    },
    m1205_commando: {
      id: "m1205_commando",
      name: "M1205 Commando Submachine Gun",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "Compact and reliable. A commando favorite.",
      usable: true,
      icon: "weapon_2.png",
      quantity: 1,
      damage: 13,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 6,
      restrictRole: "rifleman",
    },
    fasw_machine_gun: {
      // MG support
      id: "fasw_machine_gun",
      name: "M60 3F Machine Gun",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "Tried and true. Keeps heads down when it matters.",
      usable: true,
      icon: "weapon_55.png",
      quantity: 1,
      damage: 42,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 5,
      restrictRole: "support",
    },
  },
  rare: {},
  epic: {},
};
