import { type BallisticWeapon, ITEM_TYPES, type ItemsVolume } from "./types.ts";

export const BallisticItems: ItemsVolume<BallisticWeapon> = {
  common: {
    m5_assault_rifle: {
      id: "m5_assault_rifle",
      name: "M5 Assault Rifle",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "Standard-issue Infantry Rifle.",
      usable: true,
      icon: "weapon_57.png",
      quantity: 1,
      damage: 10,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 6,
    },
    hunting_rifle: {
      id: "hunting_rifle",
      name: "Old Hunting Rifle",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "Common hunting rifle.",
      usable: true,
      icon: "weapon_53.png",
      quantity: 1,
      damage: 11,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 2,
    },
    damaged_war_rifle: {
      id: "damaged_war_rifle",
      name: "Old War Rifle",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "This baby has seen some action.",
      usable: true,
      icon: "weapon_39.png",
      quantity: 1,
      damage: 9,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 3,
    },
    m240_delta_machine_gun: {
      // MG support
      id: "m240_delta_machine_gun",
      name: "M240 Delta Pattern Machine Gun",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "Highly accurate and suppressive machine gun.",
      usable: true,
      icon: "weapon_45.png",
      quantity: 1,
      damage: 29,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 7,
      restrictRole: "support",
    },
    s44_galt: {
      id: "s44_galt",
      name: "S44 Galt Carbine",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description:
        "Developed in former Belgium, this mid-range carbine is a staple for light infantry.",
      usable: true,
      icon: "weapon_29.png",
      quantity: 1,
      damage: 9,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 7,
    },
    m16_a6_assault_rifle: {
      id: "m16_a6_assault_rifle",
      name: "M16 A6",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "A battle-tested classic with a few modern enhancements.",
      usable: true,
      icon: "weapon_23.png",
      quantity: 1,
      damage: 11,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 6,
    },
    double_barrel_shotgun: {
      id: "double_barrel_shotgun",
      name: "Double barrel shotgun",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description:
        "Not very practical on the modern battlefield, but it packs a punch!",
      usable: true,
      icon: "weapon_43.png",
      quantity: 1,
      damage: 12,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 1,
    },
    m201_automatic_shotgun: {
      id: "m201_automatic_shotgun",
      name: "M201 Automatic Shotgun",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description:
        "Developed for the law enforcement sector, this highly reliable shotgun serves as an" +
        " assault weapon in close quarters combat.",
      usable: true,
      icon: "weapon_28.png",
      quantity: 1,
      damage: 20,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 4,
    },
    lsaw_guardsman: {
      id: "lsaw_guardsman",
      name: "LSAW Guardsman Rifle",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description:
        "High caliber counter sniping rifle for the professional on the move.",
      usable: true,
      icon: "weapon_34.png",
      quantity: 1,
      damage: 29,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 2,
    },
    akpd_assault_rifle: {
      id: "akpd_assault_rifle",
      name: "AK PD-2 Assault Rifle",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description:
        "Based on the venerable AK-47, this rifle boasts a higher rate of fire.",
      usable: true,
      icon: "weapon_14.png",
      quantity: 1,
      damage: 8,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 8,
    },
    m1205_commando: {
      id: "m1205_commando",
      name: "M1205 Commando Submachine Gun",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description:
        "Compact and reliable, this submachine gun is capable of horrific damage.",
      usable: true,
      icon: "weapon_2.png",
      quantity: 1,
      damage: 11,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 6,
    },
    fasw_machine_gun: {
      // MG support
      id: "fasw_machine_gun",
      name: "M60 3F Machine Gun",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description:
        "Tried and true squad assault automatic weapon system excellent for providing cover fire" +
        " and suppressing enemy combatants.",
      usable: true,
      icon: "weapon_55.png",
      quantity: 1,
      damage: 35,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 5,
      restrictRole: "support",
    },
  },
  rare: {},
  epic: {},
};
