import { type BallisticWeapon, ITEM_TYPES, type ItemsVolume } from "./types.ts";

export const BallisticItems: ItemsVolume<BallisticWeapon> = {
  common: {
    m5_assault_rifle: {
      id: "m5_assault_rifle",
      name: "M5 Assault Rifle",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "Standard-issue Infantry Rifle.",
      usable: true,
      icon: "",
      quantity: 1,
      damage: 10,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 6,
    },
    hunting_rifle: {
      id: "hunting_rifle",
      name: "Hunting Rifle",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "Common hunting rifle.",
      usable: true,
      icon: "",
      quantity: 1,
      damage: 11,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 2,
    },
    damaged_war_rifle: {
      id: "damaged_war_rifle",
      name: "War Rifle",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description: "This baby has seen some action.",
      usable: true,
      icon: "",
      quantity: 1,
      damage: 9,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 3,
    },
    s44_galt: {
      id: "s44_galt",
      name: "S44 Galt Carbine",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description:
        "Developed in former Belgium, this mid-range carbine is a staple for light infantry.",
      usable: true,
      icon: "",
      quantity: 1,
      damage: 9,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 7,
    },
    double_barrel_shotgun: {
      id: "double_barrel_shotgun",
      name: "Double barrel shotgun",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description:
        "Usually hanging over a fireplace in a log cabin, but now in your hands.",
      usable: true,
      icon: "",
      quantity: 1,
      damage: 12,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 1,
    },
    m201_automatic_shotgun: {
      id: "m201_automatic_shotgun",
      name: "M201 Automatic Shotgun",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description:
        "Developed for the law enforcement sector, this highly reliable shotgun serves as an" +
        " assault weapon in close quarters combat.",
      usable: true,
      icon: "",
      quantity: 1,
      damage: 20,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 4,
    },
    lsaw_guardsman: {
      id: "lsaw_guardsman",
      name: "LSAW Guardsman Rifle",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description:
        "High caliber counter sniping rifle for the professional on the move.",
      usable: true,
      icon: "",
      quantity: 1,
      damage: 28,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 3,
    },
    apd_assault_rifle: {
      id: "apd_assault_rifle",
      name: "APD-2 Assault Rifle",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description:
        "Based on the venerable AK-47, this rifle boasts a higher rate of fire.",
      usable: true,
      icon: "weapon_23.png",
      quantity: 1,
      damage: 8,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 8,
    },
    m1205_commando: {
      id: "m1205_commando",
      name: "M1205 Commando Submachine Gun",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description:
        "Compact and reliable, this submachine gun is capable of horrific damage.",
      usable: true,
      icon: "weapon_9.png",
      quantity: 1,
      damage: 11,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 6,
    },
    fasw_machine_gun: {
      id: "fasw_machine_gun",
      name: "FASW Machine Gun",
      type: ITEM_TYPES.ballistic_weapon,
      rarity: "common",
      description:
        "Tried and true squad assault automatic weapon system excellent for providing cover fire" +
        " and suppressing enemy combatants.",
      usable: true,
      icon: "weapon_27.png",
      quantity: 1,
      damage: 16,
      damage_type: "ballistic",
      target: "enemy",
      speed_base: 5,
    },
  },
  rare: {},
  epic: {},
};
