import {
  ITEM_TYPES,
  type ItemsVolume,
  type JunkItem,
  RARITY,
} from "./types.ts";

export const Junk: ItemsVolume<JunkItem> = {
  common: {
    pencil: {
      id: "pencil",
      name: "A Pencil",
      type: ITEM_TYPES.junk,
      description: "There are visible bite marks on the body of the pencil.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    pocket_lint: {
      id: "pocket_lint",
      name: "Some Pocket Lint",
      type: ITEM_TYPES.junk,
      description: "No doubt from the dryer.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 1,
    },
    unpaid_parking_ticket: {
      id: "unpaid_parking_ticket",
      name: "Unpaid Parking Ticket",
      type: ITEM_TYPES.junk,
      description: "The due date was 3 years ago.",
      usable: false,
      target: "none",
      price: 1,
    },
    penny: {
      id: "penny",
      name: "An Old Penny",
      type: ITEM_TYPES.junk,
      description: "The year reads 2004.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 1,
    },
    game_controller: {
      id: "game_controller",
      name: "PS2 Controller",
      type: ITEM_TYPES.junk,
      description: "The buttons are sticky, gross.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 7,
    },
    handkerchief: {
      id: "handkerchief",
      name: "A Handkerchief",
      type: ITEM_TYPES.junk,
      description: "You notice the initials 'VC', embroidered in the corner.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
    gum_wrapper: {
      id: "gum_wrapper",
      name: "Gum Wrapper",
      type: ITEM_TYPES.junk,
      description: "Succulent Fruits gum wrapper",
      usable: false,
      rarity: "common",
      target: "none",
      price: 1,
    },
    virus_test_kit: {
      id: "virus_test_kit",
      name: "Viral Test Kit",
      type: ITEM_TYPES.junk,
      description:
        "The item appears to be part of a kit of 12.  No doubt the owner was very" +
        " concerned with catching a virus.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 4,
    },
    rusty_paperclip: {
      id: "rusty_paperclip",
      name: "Rusty Paperclip",
      type: ITEM_TYPES.junk,
      description: "",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    paperclip: {
      id: "paperclip",
      name: "Shiny Paperclip",
      type: ITEM_TYPES.junk,
      description: "",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    expired_coupon: {
      id: "expired_coupon",
      name: "Expired Coupon",
      type: ITEM_TYPES.junk,
      description: "10% off toilet paper... in 2019. A relic of better times.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    single_sock: {
      id: "single_sock",
      name: "Lonely Sock",
      type: ITEM_TYPES.junk,
      description: "Its partner vanished in a tragic dryer accident.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 4,
    },
    glitter_bomb_remnants: {
      id: "glitter_bomb_remnants",
      name: "Glitter Bomb Remnants",
      type: ITEM_TYPES.junk,
      description: "Still sparkly. Still everywhere. Forever.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    empty_chapstick: {
      id: "empty_chapstick",
      name: "Empty Chapstick Tube",
      type: ITEM_TYPES.junk,
      description: "You twisted it ten more times just to be sure.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
    bent_spoon: {
      id: "bent_spoon",
      name: "Bent Spoon",
      type: ITEM_TYPES.junk,
      description: "Maybe you *are* The One.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 6,
    },
    broken_usb: {
      id: "broken_usb",
      name: "Broken USB Stick",
      type: ITEM_TYPES.junk,
      description: "Contains 3kb of corrupted homework from 2007.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 4,
    },
    fake_mustache: {
      id: "fake_mustache",
      name: "Fake Mustache",
      type: ITEM_TYPES.junk,
      description: "Perfect for going incognito or confusing children.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
    fortune_cookie: {
      id: "fortune_cookie",
      name: "Fortune Cookie",
      type: ITEM_TYPES.junk,
      description: "‘Help! I'm trapped in a game item factory!’",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    tiny_top_hat: {
      id: "tiny_top_hat",
      name: "Tiny Top Hat",
      type: ITEM_TYPES.junk,
      description:
        "Unclear whether it was meant for a rodent or a baby aristocrat.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
    kazoo_of_doom: {
      id: "kazoo_of_doom",
      name: "Kazoo of Doom",
      type: ITEM_TYPES.junk,
      description: "It squeaks. It squeals. It is deeply cursed.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 4,
    },
    emergency_whistle: {
      id: "emergency_whistle",
      name: "Emergency Whistle",
      type: ITEM_TYPES.junk,
      description: "Does not work. Causes mild confusion instead.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 8,
    },
    commemorative_mug: {
      id: "commemorative_mug",
      name: "World's Okayest Soldier Mug",
      type: ITEM_TYPES.junk,
      description: "Clearly re-gifted. Three times.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
    novelty_toilet_paper: {
      id: "novelty_toilet_paper",
      name: "Toilet Paper (Scented, Glows)",
      type: ITEM_TYPES.junk,
      description: "Scented like fear. Glows like regret.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 4,
    },
    plastic_fork: {
      id: "plastic_fork",
      name: "Plastic Fork",
      type: ITEM_TYPES.junk,
      description: "One tine is bent. It's basically a trident.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 1,
    },
    lint_ball: {
      id: "lint_ball",
      name: "Massive Lint Ball",
      type: ITEM_TYPES.junk,
      description: "You don’t remember collecting this. No one does.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    broken_watch: {
      id: "broken_watch",
      name: "Broken Wristwatch",
      type: ITEM_TYPES.junk,
      description: "Still stuck at 4:20. Nice.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
    cracked_phone: {
      id: "cracked_phone",
      name: "Obsolete Smartphone",
      type: ITEM_TYPES.junk,
      description: "Used to play Snake and ruin attention spans.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 4,
    },
    fidget_spinner: {
      id: "fidget_spinner",
      name: "Ancient Fidget Spinner",
      type: ITEM_TYPES.junk,
      description: "Unearthed from the ruins of 2017.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 5,
    },
    cursed_doll_head: {
      id: "cursed_doll_head",
      name: "Cursed Doll Head",
      type: ITEM_TYPES.junk,
      description: "Why is it looking at you like that?",
      usable: false,
      rarity: "common",
      target: "none",
      price: 4,
    },
    ironic_tshirt: {
      id: "ironic_tshirt",
      name: "Ironic T-Shirt (Size XS)",
      type: ITEM_TYPES.junk,
      description: "Says ‘NPC Lives Matter’. It's tight... socially.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 5,
    },
    empty_energy_drink: {
      id: "empty_energy_drink",
      name: "Empty Energy Drink Can",
      type: ITEM_TYPES.junk,
      description: "You already used its +1 attention span buff.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
    half_eaten_burrito: {
      id: "half_eaten_burrito",
      name: "Half-Eaten Burrito",
      type: ITEM_TYPES.junk,
      description: "Still warm. Still questionable.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    romance_novel: {
      id: "romance_novel",
      name: "Torn Romance Novel",
      type: ITEM_TYPES.junk,
      description: "Chapter 9 is missing. That was the good part.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 8,
    },
    plastic_eye: {
      id: "plastic_eye",
      name: "Loose Plastic Eye",
      type: ITEM_TYPES.junk,
      description: "Winks when you’re not looking.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    floppy_disk: {
      id: "floppy_disk",
      name: "Floppy Disk (Unknown Format)",
      type: ITEM_TYPES.junk,
      description: "Contains 'Cool Pics' — probably just Clipart.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
    movie_ticket_stub: {
      id: "movie_ticket_stub",
      name: "Movie Ticket Stub",
      type: ITEM_TYPES.junk,
      description: "‘Transformers 2’. A decision was made.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 1,
    },
    fake_id: {
      id: "fake_id",
      name: "Fake ID",
      type: ITEM_TYPES.junk,
      description: "Says you're 47. You are not 47.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 5,
    },
    glitter_pen: {
      id: "glitter_pen",
      name: "Glitter Pen (Dried Out)",
      type: ITEM_TYPES.junk,
      description: "Writes nothing but dreams.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 6,
    },
    empty_snack_wrapper: {
      id: "empty_snack_wrapper",
      name: "Empty Snack Wrapper",
      type: ITEM_TYPES.junk,
      description: "Crinkly. Loud. Useless. Much like its owner.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 1,
    },
    souvenir_spoon: {
      id: "souvenir_spoon",
      name: "Souvenir Spoon (Niagara Falls)",
      type: ITEM_TYPES.junk,
      description: "A tiny monument to a big disappointment.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
    novelty_keychain: {
      id: "novelty_keychain",
      name: "Light-Up Keychain",
      type: ITEM_TYPES.junk,
      description: "No light. No keys. Just vibes.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 4,
    },
    bottle_of_sand: {
      id: "bottle_of_sand",
      name: "Tiny Bottle of Sand",
      type: ITEM_TYPES.junk,
      description: "From someone's 'life-changing' beach trip.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 4,
    },
    cracked_mirror: {
      id: "cracked_mirror",
      name: "Cracked Mirror Shard",
      type: ITEM_TYPES.junk,
      description: "Seven years of bad hair days.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    yo_yo: {
      id: "yo_yo",
      name: "Dusty Yo-Yo",
      type: ITEM_TYPES.junk,
      description: "You're no longer the cool kid who could ‘Walk the Dog’.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 8,
    },
    broken_lighter: {
      id: "broken_lighter",
      name: "Dead Lighter",
      type: ITEM_TYPES.junk,
      description: "You flicked it. Nothing happened. Repeat.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
    used_scratch_ticket: {
      id: "used_scratch_ticket",
      name: "Loser Scratch Ticket",
      type: ITEM_TYPES.junk,
      description: "Someone gambled and lost. Now it’s yours!",
      usable: false,
      rarity: "common",
      target: "none",
      price: 1,
    },
    anime_sticker: {
      id: "anime_sticker",
      name: "Peeling Anime Sticker",
      type: ITEM_TYPES.junk,
      description: "From the legendary show ‘Magical Cat Dentist Z’.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 1,
    },
    vhs_tape: {
      id: "vhs_tape",
      name: "VHS Tape (Unlabeled)",
      type: ITEM_TYPES.junk,
      description: "Play it... if you dare. Or have a VCR.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
    broken_action_figure: {
      id: "broken_action_figure",
      name: "Action Figure (Missing Head)",
      type: ITEM_TYPES.junk,
      description: "Still more expressive than the movie version.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 5,
    },
    friendship_bracelet: {
      id: "friendship_bracelet",
      name: "Worn-Out Friendship Bracelet",
      type: ITEM_TYPES.junk,
      description: "Who gave this to you? Why does it smell like sadness?",
      usable: false,
      rarity: "common",
      target: "none",
      price: 5,
    },
    hoverboard_brochure: {
      id: "hoverboard_brochure",
      name: "Hoverboard Brochure",
      type: ITEM_TYPES.junk,
      description: "Still says 'Coming in 2015!' in Comic Sans.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    flux_capacitor_manual: {
      id: "flux_capacitor_manual",
      name: "Flux Capacitor Manual",
      type: ITEM_TYPES.junk,
      description: "Requires 1.21 gigawatts and poor decision-making.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 4,
    },
    neo_sunglasses: {
      id: "neo_sunglasses",
      name: "Neo's Sunglasses",
      type: ITEM_TYPES.junk,
      description: "They only work if you believe you’re The One.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 7,
    },
    red_pill_candy: {
      id: "red_pill_candy",
      name: "Suspicious Red Candy",
      type: ITEM_TYPES.junk,
      description: "Not FDA approved. Reality distortion may occur.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
    terminator_hand: {
      id: "terminator_hand",
      name: "Metallic Robotic Hand",
      type: ITEM_TYPES.junk,
      description: "It's cold. It's heavy. It wants your clothes.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 6,
    },
    proton_pack_warning: {
      id: "proton_pack_warning",
      name: "Proton Pack Safety Notice",
      type: ITEM_TYPES.junk,
      description: "Whatever you do, **don't cross the streams**.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 1,
    },
    ghost_trap_coupon: {
      id: "ghost_trap_coupon",
      name: "Ghost Trap Rental Coupon",
      type: ITEM_TYPES.junk,
      description: "Expired. Plus, you ain't afraid of no ghost.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    gremlin_diet_chart: {
      id: "gremlin_diet_chart",
      name: "Gremlin Feeding Instructions",
      type: ITEM_TYPES.junk,
      description: "Rule #1: Don’t feed them after midnight. Ever.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    goonies_map_fragment: {
      id: "goonies_map_fragment",
      name: "Old Treasure Map Fragment",
      type: ITEM_TYPES.junk,
      description: "Hey you guyyyyys... it’s missing the best part.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 4,
    },
    crumpled_note: {
      id: "crumpled_note",
      name: "Crumpled Note",
      type: ITEM_TYPES.junk,
      description: "Illegible. Possibly important. Probably not.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    slightly_warm_rock: {
      id: "slightly_warm_rock",
      name: "Slightly Warm Rock",
      type: ITEM_TYPES.junk,
      description: "Feels like it was sitting in someone’s pocket too long.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 5,
    },
    mystery_powder: {
      id: "mystery_powder",
      name: "Unlabeled Mystery Powder",
      type: ITEM_TYPES.junk,
      description: "It’s white. It’s fine. It’s not your problem anymore.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    safety_brochure: {
      id: "safety_brochure",
      name: "Outdated Safety Brochure",
      type: ITEM_TYPES.junk,
      description: "Instructions for technology that no longer exists.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
    broken_button: {
      id: "broken_button",
      name: "Broken Button",
      type: ITEM_TYPES.junk,
      description: "Not from clothing. Not from electronics. Just... a button.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
    melted_crayon: {
      id: "melted_crayon",
      name: "Melted Crayon",
      type: ITEM_TYPES.junk,
      description: "The color is ‘Regret Red’.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    pocket_air: {
      id: "pocket_air",
      name: "Pocket Full of Air",
      type: ITEM_TYPES.junk,
      description: "Perfectly preserved pocket atmosphere. Do not inhale.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    tangle_of_wires: {
      id: "tangle_of_wires",
      name: "Tangled Wires",
      type: ITEM_TYPES.junk,
      description: "No known device accepts these. Good luck.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
    rubber_band_ball: {
      id: "rubber_band_ball",
      name: "Rubber Band Ball",
      type: ITEM_TYPES.junk,
      description: "Technically an accomplishment. Functionally useless.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 4,
    },
    half_sticker: {
      id: "half_sticker",
      name: "Half of a Sticker",
      type: ITEM_TYPES.junk,
      description: "It says ‘Good J’. Someone tried.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 1,
    },

    jurassic_park_ticket: {
      id: "jurassic_park_ticket",
      name: "Jurassic Park Admit One",
      type: ITEM_TYPES.junk,
      description: "Slightly torn. Definitely eaten.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 1,
    },
    vhs_labeled_titanic: {
      id: "vhs_labeled_titanic",
      name: "Titanic (VHS - Part 1)",
      type: ITEM_TYPES.junk,
      description: "Where's part 2? WHERE’S PART 2?!",
      usable: false,
      rarity: "common",
      target: "none",
      price: 1,
    },
    adam_sandler_dvd: {
      id: "adam_sandler_dvd",
      name: "Click (Scratched DVD)",
      type: ITEM_TYPES.junk,
      description: "You tried to pause life. Instead, it skipped.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
    matrix_boot_disc: {
      id: "matrix_boot_disc",
      name: "Matrix Reboot Disc",
      type: ITEM_TYPES.junk,
      description: "Now compatible with Windows 98.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 4,
    },
    empty_ring_box: {
      id: "empty_ring_box",
      name: "Ring Box (Missing Ring)",
      type: ITEM_TYPES.junk,
      description: "The one ring was definitely here. You feel watched.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
    legolas_action_card: {
      id: "legolas_action_card",
      name: "Legolas Trading Card",
      type: ITEM_TYPES.junk,
      description: "Perfect hair. Perfect aim. Bent corner.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    hobbit_recipe_scroll: {
      id: "hobbit_recipe_scroll",
      name: "Scroll of Second Breakfast",
      type: ITEM_TYPES.junk,
      description: "Includes elevensies and afternoon tea.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 5,
    },
    toy_lightsaber: {
      id: "toy_lightsaber",
      name: "Plastic Lightsaber (Blue)",
      type: ITEM_TYPES.junk,
      description: "Makes a ‘whoosh’ sound if you swing hard enough.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 5,
    },
    darth_vhs_box: {
      id: "darth_vhs_box",
      name: "Star Wars VHS Box (Trilogy)",
      type: ITEM_TYPES.junk,
      description: "Han shot first. You have proof.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 6,
    },
    mi_disguise_kit: {
      id: "mi_disguise_kit",
      name: "Mini Disguise Kit (MI:1)",
      type: ITEM_TYPES.junk,
      description: "Your mission, should you choose to fail, is cosmetic.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 2,
    },
    mulder_photo: {
      id: "mulder_photo",
      name: "Faded FBI Badge Photo",
      type: ITEM_TYPES.junk,
      description: "The truth is in here. Somewhere.",
      usable: false,
      rarity: "common",
      target: "none",
      price: 3,
    },
  },
  rare: {
    encyclopedia: {
      id: "encyclopedia",
      name: "Tattered Encyclopedia",
      type: ITEM_TYPES.junk,
      description: "The written word is a powerful tool.",
      usable: false,
      rarity: RARITY.rare,
      target: "none",
      price: 30,
    },
    book_1984: {
      id: "book_1984",
      name: "George Orwell's 1984",
      type: ITEM_TYPES.junk,
      description:
        "1984 serves as a critique of authoritarianism.  The book is tattered, page 84 is missing.",
      usable: false,
      rarity: RARITY.rare,
      target: "none",
      price: 20,
    },
    purple_furby: {
      id: "purple_furby",
      name: "Purple Furby Doll",
      type: ITEM_TYPES.junk,
      description:
        "A fluffy toy with funny looking eyes, it's certainly not a recording device.",
      usable: false,
      rarity: RARITY.rare,
      target: "none",
      price: 40,
    },
    vintage_furby: {
      id: "purple_furby",
      name: "Vintage Pink Furby Doll",
      type: ITEM_TYPES.junk,
      description:
        "A fluffy toy with funny looking eyes, it's certainly not a recording device.",
      usable: false,
      rarity: RARITY.rare,
      target: "none",
      price: 110,
    },
    galaxy_furby: {
      id: "purple_furby",
      name: "Galaxy Edition Furby Doll",
      type: ITEM_TYPES.junk,
      description:
        "A fluffy toy with funny looking eyes, it's certainly not a recording device.",
      usable: false,
      rarity: RARITY.rare,
      target: "none",
      price: 80,
    },
    tie_dye_furby: {
      id: "purple_furby",
      name: "Tie Dye Furby Doll",
      type: ITEM_TYPES.junk,
      description:
        "A fluffy toy with funny looking eyes, it's certainly not a recording device.",
      usable: false,
      rarity: RARITY.rare,
      target: "none",
      price: 60,
    },
    half_empty_bottle_of_nsaid: {
      id: "half_empty_bottle_of_nsaid",
      name: "Anti-Inflammatory Drug",
      type: ITEM_TYPES.junk,
      description:
        "Reduce pain and inflammation. The bottle is nearly empty. Expired 12 years ago.  Might" +
        " still work!",
      usable: false,
      rarity: RARITY.rare,
      target: "none",
      price: 50,
    },
  },
  epic: {
    willie_mays_trading_card: {
      id: "willie_mays_trading_card",
      name: "Tattered Encyclopedia",
      type: ITEM_TYPES.junk,
      description:
        "You can make out some faint lettering... 1953... Topps #244...",
      usable: false,
      rarity: RARITY.epic,
      target: "none",
      price: 1600,
    },
    platinum_ingot: {
      id: "platinum_ingot",
      name: "Platinum Ingot",
      type: ITEM_TYPES.junk,
      description: "Platinum 999.5, someone was a savvy investor.",
      usable: false,
      rarity: RARITY.epic,
      target: "none",
      price: 1100,
    },
    paul_newman_daytona: {
      id: "paul_newman_daytona",
      name: "Paul Newman Daytona",
      type: ITEM_TYPES.junk,
      description:
        "You see a faint engraving on the back: '6241 Paul Newman Daytona'.",
      usable: false,
      rarity: RARITY.epic,
      target: "none",
      price: 2800,
    },
  },
};
