import {
  ITEM_TYPES,
  type ItemsVolume,
  RARITY,
  type ThrowableItem,
} from "./types.ts";
import { DAMAGE_TYPES } from "../types.ts";

export const ThrowableItems: ItemsVolume<ThrowableItem> = {
  common: {
    m3_frag_grenade: {
      id: "m3_frag_grenade",
      name: "M3 Frag Grenade",
      type: ITEM_TYPES.throwable,
      rarity: "common",
      description:
        "30 explosive damage to primary target. Adjacent enemies take 50% splash damage.",
      usable: true,
      uses: 5,
      damage: 30,
      damage_type: "explosive",
      icon: "throwable_0.png",
      target: "enemy_area",
      tags: ["explosive", "throwable"],
    },
    m84_flashbang: {
      id: "m84_flashbang",
      name: "M84 Flashbang",
      type: ITEM_TYPES.throwable,
      rarity: "common",
      description:
        "Non-lethal stun grenade. Disorients and incapacitates targets in an area.",
      usable: true,
      uses: 5,
      damage: 0,
      damage_type: "explosive",
      tags: ["psychological", "throwable", "stun"],
      icon: "throwable_6.png",
      target: "enemy_area",
      effect: {
        type: "debuff",
        duration: 4,
        effectiveness: 5,
        result: "stun",
        description:
          "Temporarily incapacitates with a loud bang and intense flash.",
      },
    },
    mk18_smoke: {
      id: "mk18_smoke",
      name: "MK-18 Smoke Grenade",
      type: ITEM_TYPES.throwable,
      rarity: "common",
      description:
        "Dense smoke obscures vision and reduces accuracy in the target area.",
      usable: true,
      uses: 5,
      damage: 0,
      damage_type: "chemical",
      icon: "throwable_3.png",
      target: "enemy_area",
      tags: ["psychological", "throwable", "smoke"],
    },
    incendiary_grenade: {
      id: "incendiary_grenade",
      name: "HE7 Incendiary Grenade",
      type: ITEM_TYPES.throwable,
      rarity: "common",
      description:
        "Napalm grenade. Showers the area in burning gel that ignores armor.",
      usable: true,
      uses: 5,
      damage: 0,
      damage_type: "explosive",
      icon: "throwable_4.png",
      target: "enemy_area",
      tags: ["thermal", "throwable"],
      effect: {
        type: "debuff",
        duration: 4,
        effectiveness: 4,
        result: "burn",
        effect_value: 8,
        description: "8 dmg/sec, 4 ticks.",
      },
    },
    nbc_neutralizer: {
      id: "nbc_neutralizer",
      name: "NBC Neutralizer",
      type: ITEM_TYPES.throwable,
      damage_type: DAMAGE_TYPES.neutral,
      rarity: "common",
      description: "Counter-agent that clears Nuclear, Biological, and Chemical hazards from allies.",
      usable: true,
      uses: 5,
      icon: "throwable_7.png",
      target: "friendly_area",
      tags: ["neutralizer", "throwable"],
      effect: {
        type: "buff",
        duration: 1,
        effectiveness: 10,
        result: "cleansing",
        description:
          "Cancels remaining effect duration of nuclear, chemical, and biological" +
          " agents.",
      },
    },
    tk21_throwing_knife: {
      id: "tk21_throwing_knife",
      name: "TK-21 Throwing Knife",
      type: ITEM_TYPES.throwable,
      rarity: "common",
      description:
        "20 kinetic damage to a single enemy. No splash. Uses thrower's accuracy.",
      usable: true,
      uses: 10,
      damage: 20,
      damage_type: "kinetic",
      icon: "throwable_8.png",
      target: "enemy",
      tags: ["kinetic", "throwable"],
    },
  },
  rare: {
    m3a_frag_grenade: {
      id: "m3_frag_grenade",
      name: "M3A Fragmentation Grenade",
      type: ITEM_TYPES.throwable,
      rarity: RARITY.rare,
      flavor: "Upgraded frag with a heavier casing. Popular with demolition crews.",
      description:
        "45 explosive damage to primary target. Adjacent enemies take 50% splash damage.",
      usable: true,
      uses: 5,
      damage: 45,
      damage_type: "explosive",
      icon: "throwable_9.png",
      target: "enemy_area",
      tags: ["explosive", "throwable"],
    },
    m99_sticky_grenade: {
      id: "m99_sticky_grenade",
      name: "M99 Sticky Grenade",
      type: ITEM_TYPES.throwable,
      rarity: RARITY.rare,
      flavor: "Adhesive compound keeps it latched until detonation. No friendlies in the blast—just the target.",
      description: "Explosive that adheres to the target. No collateral damage.",
      usable: true,
      uses: 5,
      damage: 80,
      damage_type: "explosive",
      icon: "throwable_5.png",
      target: "enemy",
      tags: ["explosive", "throwable"],
    },
    nerve_gas_detonator: {
      id: "nerve_gas_detonator",
      name: "CM55 Nerve Gas Detonator",
      type: ITEM_TYPES.throwable,
      rarity: RARITY.rare,
      flavor: "Classified chemical payload. Breaks down nervous response—effective but controversial.",
      description: "Chemical agent that inflicts poison damage over time.",
      usable: true,
      uses: 5,
      damage: 0,
      damage_type: "chemical",
      tags: ["chemical", "throwable"],
      icon: "throwable_1.png",
      target: "enemy_area",
      effect: {
        type: "debuff",
        effect_value: 20,
        duration: 2,
        effectiveness: 7,
        result: "poison",
      },
    },
    m3a_repressor: {
      id: "m3a_repressor",
      name: "M3A Repressor",
      type: ITEM_TYPES.throwable,
      rarity: RARITY.rare,
      flavor: "Suppression ordinance that weakens armor integrity. Favored for softening hardened targets before the push.",
      description:
        "10 explosive damage. Primary: 80% toughness reduction for 8s. Adjacent: evade or suffer 20% toughness reduction for 4s; no splash damage.",
      usable: true,
      uses: 5,
      damage: 10,
      damage_type: "explosive",
      icon: "throwable_9.png",
      target: "enemy_area",
      tags: ["explosive", "throwable"],
      effect: {
        type: "debuff",
        duration: 8,
        effectiveness: 7,
        result: "toughness_reduced",
        effect_value: 80,
        description: "Reduces toughness by 80% for 8 seconds.",
      },
    },
    rad_emitter: {
      id: "rad_emitter",
      name: "Radiation Pulse Emitter",
      type: ITEM_TYPES.throwable,
      rarity: RARITY.rare,
      flavor: "Compact rad generator. The glow is harmless—the aftermath is not.",
      description: "Emits a pulse of radiation that causes lingering damage.",
      usable: true,
      uses: 5,
      damage: 0,
      damage_type: "radiation",
      icon: "throwable_10.png",
      target: "enemy_area",
      tags: ["radiation", "throwable"],
      effect: {
        type: "debuff",
        effect_value: 5,
        duration: 4,
        effectiveness: 6,
        result: "burn",
        description: "Applies radiation burns over time.",
      },
    },
  },
  epic: {
    mind_ripper: {
      id: "psychic_shredder",
      name: "Psychic Shredder",
      type: ITEM_TYPES.throwable,
      rarity: "epic",
      flavor: "Psionic amplifier that channels raw dread. Survivors report hearing their own worst fears before the panic sets in.",
      description: "Psychic weapon that induces panic and breaks enemy morale.",
      usable: true,
      uses: 5,
      damage: 0,
      damage_type: "psychological",
      icon: "throwable_2.png",
      target: "enemy_area",
      tags: ["psychological", "throwable"],
      effect: {
        type: "debuff",
        effect_value: 3,
        duration: 6,
        effectiveness: 8,
        result: "panic",
        description: "Direct: 6s panic. Adjacent: 3s if evade fails.",
      },
    },
  },
};
