import {
  ITEM_TYPES,
  type ItemsVolume,
  RARITY,
  type ThrowableItem,
} from "./types.ts";
import { DAMAGE_TYPES } from "../types.ts";

export const ThrowableItems: ItemsVolume<ThrowableItem> = {
  common: {
    m3_frag_grenade: {
      id: "m3_frag_grenade",
      name: "M3 Fragmentation Grenade",
      type: ITEM_TYPES.throwable,
      rarity: "common",
      description:
        "Standard-issue fragmentation grenade used to clear enemy positions.",
      usable: true,
      damage: 60,
      damage_type: "explosive",
      icon: "throwable_0.png",
      target: "enemy_area",
      tags: ["explosive", "throwable"],
    },
    m84_flashbang: {
      id: "m84_flashbang",
      name: "M84 Flashbang",
      type: ITEM_TYPES.throwable,
      rarity: "common",
      description:
        "Non-lethal stun grenade used for room clearing and disorientation.",
      usable: true,
      damage: 2,
      damage_type: "explosive",
      tags: ["psychological", "throwable"],
      icon: "throwable_6.png",
      target: "enemy_area",
      effect: {
        type: "debuff",
        duration: 3,
        effectiveness: 5,
        result: "confusion",
        description:
          "Temporarily incapacitates with a loud bang and intense flash.",
      },
    },
    mk18_smoke: {
      id: "mk18_smoke",
      name: "MK-18 Smoke Grenade",
      type: ITEM_TYPES.throwable,
      rarity: "common",
      description:
        "Creates a thick smoke screen to obscure vision and movement.",
      usable: true,
      quantity: 1,
      damage: 0,
      damage_type: "chemical",
      icon: "throwable_3.png",
      target: "enemy_area",
      effect: {
        type: "debuff",
        duration: 3,
        effectiveness: 4,
        result: "concealment",
        description: "Temporarily conceals you with smoke.",
      },
      tags: ["psychological", "throwable"],
    },
    incendiary_grenade: {
      id: "incendiary_grenade",
      name: "HE7 Incendiary Grenade",
      type: ITEM_TYPES.throwable,
      rarity: "common",
      description:
        "High explosive napalm grenade, showers effective area with highly flammable napalm gel" +
        " upon detonation.",
      usable: true,
      quantity: 1,
      damage: 35,
      damage_type: "explosive",
      icon: "throwable_3.png",
      target: "enemy_area",
      tags: ["thermal", "throwable"],
      effect: {
        type: "debuff",
        duration: 3,
        effectiveness: 4,
        result: "burn",
        effect_value: 12,
        description: "It's simple, but effective.",
      },
    },
    nbc_neutralizer: {
      id: "nbc_neutralizer",
      name: "NBC Neutralizer",
      type: ITEM_TYPES.throwable,
      damage_type: DAMAGE_TYPES.neutral,
      rarity: "common",
      description: "Neutralized Nuclear, Biological and Chemical gases.",
      usable: true,
      quantity: 1,
      icon: "throwable_3.png",
      target: "friendly_area",
      tags: ["neutralizer", "throwable"],
      effect: {
        type: "buff",
        duration: 1,
        effectiveness: 10,
        result: "cleansing",
        description:
          "Cancels remaining effect duration of nuclear, chemical, and biological" +
          " agents.",
      },
    },
    tk21_throwing_knife: {
      id: "tk21_throwing_knife",
      name: "TK-21 Throwing Knife",
      type: ITEM_TYPES.throwable,
      rarity: "common",
      description:
        "Lightweight carbon blade balanced for silent kills at short range.",
      usable: true,
      quantity: 1,
      damage: 35,
      damage_type: "kinetic",
      icon: "throwable_3.png",
      target: "enemy",
      tags: ["kinetic", "throwable"],
    },
  },
  rare: {
    m3a_frag_grenade: {
      id: "m3_frag_grenade",
      name: "M3A Fragmentation Grenade",
      type: ITEM_TYPES.throwable,
      rarity: RARITY.rare,
      description:
        "An improvement on the standard-issue fragmentation grenade.",
      usable: true,
      quantity: 1,
      damage: 80,
      damage_type: "explosive",
      icon: "throwable_0.png",
      target: "enemy_area",
      tags: ["explosive", "throwable"],
    },
    m99_sticky_grenade: {
      id: "m99_sticky_grenade",
      name: "M99 Sticky Grenade",
      type: ITEM_TYPES.throwable,
      rarity: RARITY.rare,
      description: "Sticks to your opponent.",
      usable: true,
      quantity: 1,
      damage: 80,
      damage_type: "explosive",
      icon: "throwable_5.png",
      target: "enemy",
      tags: ["explosive", "throwable"],
    },
    nerve_gas_vial: {
      id: "nerve_gas_vial",
      name: "Nerve Gas Vial",
      type: ITEM_TYPES.throwable,
      rarity: RARITY.rare,
      description: "A vile chemical agent that burns the skin.",
      usable: true,
      quantity: 1,
      damage: 0,
      damage_type: "chemical",
      tags: ["chemical", "throwable"],
      icon: "throwable_1.png",
      target: "enemy_area",
      effect: {
        type: "debuff",
        effect_value: 20,
        duration: 2,
        effectiveness: 7,
        result: "poison",
      },
    },
    rad_emitter: {
      id: "rad_emitter",
      name: "Radiation Pulse Emitter",
      type: ITEM_TYPES.throwable,
      rarity: RARITY.rare,
      description: "Emits a burst of harmful radiation.",
      usable: true,
      quantity: 1,
      damage: 0,
      damage_type: "radiation",
      icon: "throwable_5.png",
      target: "enemy_area",
      tags: ["radiation", "throwable"],
      effect: {
        type: "debuff",
        effect_value: 5,
        duration: 4,
        effectiveness: 6,
        result: "burn",
        description: "Applies radiation burns over time.",
      },
    },
  },
  epic: {
    mind_ripper: {
      id: "psychic_shredder",
      name: "Psychic Shredder",
      type: ITEM_TYPES.throwable,
      rarity: "epic",
      description: "Assaults the psyche with unbearable sound invoking terror.",
      usable: true,
      quantity: 1,
      damage: 0,
      damage_type: "psychological",
      icon: "throwable_2.png",
      target: "enemy_area",
      tags: ["psychological", "throwable"],
      effect: {
        type: "debuff",
        effect_value: 3,
        duration: 2,
        effectiveness: 8,
        result: "panic",
        description: "Causes panic, reducing morale and evasion.",
      },
    },
  },
};
