export const DOM = {
  app: "#app",
  game: "#game",
  g: {
    upper: "#g-upper",
    lower: "#g-lower",
    left: "#g-left",
    menu: "#g-menu",
    right: "#g-right",
    center: "#g-center",
  },
  company: {
    home: "#company-go-home",
    market: "#company-go-market",
    roster: "#company-go-roster",
    training: "#company-go-training",
    missions: "#company-go-missions",
    inventory: "#company-go-inventory",
    heroes: "#company-go-memorial",
    abilities: "#company-go-abilities",
    all: ".company-actions button",
  },
  enterGameWrapper: "#game-enter-wrapper",
  enterGame: "#game-enter",
  setupScreen: {
    unitPatch: ".setup-game-wrapper .grid img",
    companyInput: "#company-name",
    commanderInput: "#commander-name",
    finish: "#finish-game-setup",
    cancel: "#cancel-game-setup",
  },
  mainMenu: {
    newGame: "#start-new-game",
    continue: "#continue-campaign",
    credits: "#show-credits",
    settings: "#show-settings",
  },
  confirmScreen: {
    launch: "#launch-game",
    goBack: "#go-back",
    confirmationParent: "#setup-confirmation",
  },
};
