export const DOM = {
  app: "#app",
  game: "#game",
  g: {
    upper: "#g-upper",
    lower: "#g-lower",
    left: "#g-left",
    menu: "#g-menu",
    right: "#g-right",
    center: "#g-center",
  },
  company: {
    home: "#company-go-home",
    market: "#company-go-market",
    goToTroopsScreen: "#go-to-troops-screen",
    roster: "#company-go-roster",
    training: "#company-go-training",
    missions: "#company-go-missions",
    inventory: "#company-go-inventory",
    heroes: "#company-go-memorial",
    codex: "#company-go-codex",
    statsMemorial: "#company-stats-memorial",
    codexPopup: "#codex-popup",
    codexPopupClose: "#codex-popup-close",
    abilities: "#company-go-abilities",
    all: ".company-actions button",
    rerollCounter: ".reroll-counter",
  },
  market: {
    marketTroopsLink: "#market-troops",
    marketArmorLink: "#market-armor",
    marketWeaponsLink: "#market-weapons",
    marketSuppliesLink: "#market-supplies",
    pages: {
      recruitTroops: {
        rerollSoldier: ".reroll-soldier",
        recruitSoldier: ".recruit-soldier",
        recruitStagingDiv: "#recruit-staging",
        confirmRecruitment: "#confirm-recruitment",
        removeFromStaging: ".remove-from-staging",
      },
    },
  },
  enterGameWrapper: "#game-enter-wrapper",
  enterGame: "#game-enter",
  setupScreen: {
    unitPatch: ".setup-game-wrapper .setup-patch-img",
    companyInput: "#company-name",
    commanderInput: "#commander-name",
    finish: "#finish-game-setup",
    cancel: "#cancel-game-setup",
  },
  missions: {
    launchBtn: ".mission-launch-btn",
    readMoreBtn: ".mission-card-read-more",
    flavorPopup: "#mission-flavor-popup",
    flavorPopupClose: "#mission-flavor-popup-close",
  },
  readyRoom: {
    proceedBtn: "#ready-room-proceed",
  },
  combat: {
    beginBtn: "#combat-begin",
    resetBtn: "#combat-reset",
    missionDetailsBtn: "#combat-mission-details",
    quitBtn: "#combat-quit",
    quitConfirmPopup: "#combat-quit-confirm-popup",
    quitConfirmYes: "#combat-quit-confirm-yes",
    quitConfirmNo: "#combat-quit-confirm-no",
    abilitiesPopup: "#combat-abilities-popup",
    abilitiesPopupContent: "#combat-abilities-popup-content",
    abilitiesPopupHint: "#combat-abilities-popup-hint",
    abilitiesPopupTitle: "#combat-abilities-popup-title",
    abilitiesList: "#combat-abilities-list",
    battleArea: "#combat-battle-area",
  },
  mainMenu: {
    newGame: "#start-new-game",
    continue: "#continue-campaign",
    credits: "#show-credits",
    settings: "#show-settings",
  },
  roster: {
    inventoryBtn: ".roster-inventory-btn",
    releaseBtn: ".roster-release-btn",
  },
  inventory: {
    destroyBtn: ".inventory-destroy-btn",
    itemCard: ".inventory-item-card",
    itemStatsPopup: "#item-stats-popup",
    itemStatsPopupClose: "#item-stats-popup-close",
  },
  supplies: {
    market: "#supplies-market",
    item: ".supplies-market-item",
    buyPopup: "#supplies-buy-popup",
    buyTitle: "#supplies-buy-title",
    buyBody: "#supplies-buy-body",
    buyError: "#supplies-buy-error",
    qtyInput: "#supplies-qty-input",
    qtyMinus: "#supplies-qty-minus",
    qtyPlus: "#supplies-qty-plus",
    buyBtn: "#supplies-buy-btn",
    buyClose: "#supplies-buy-close",
  },
  weapons: {
    item: ".gear-market-item[data-gear-context='weapons']",
    buyPopup: "#weapons-buy-popup",
    buyTitle: "#weapons-buy-title",
    buyBody: "#weapons-buy-body",
    qtyInput: "#weapons-qty-input",
    qtyMinus: "#weapons-qty-minus",
    qtyPlus: "#weapons-qty-plus",
    buyBtn: "#weapons-buy-btn",
    buyClose: "#weapons-buy-close",
    buyError: "#weapons-buy-error",
  },
  armor: {
    item: ".gear-market-item[data-gear-context='armor']",
    buyPopup: "#armor-buy-popup",
    buyTitle: "#armor-buy-title",
    buyBody: "#armor-buy-body",
    qtyInput: "#armor-qty-input",
    qtyMinus: "#armor-qty-minus",
    qtyPlus: "#armor-qty-plus",
    buyBtn: "#armor-buy-btn",
    buyClose: "#armor-buy-close",
    buyError: "#armor-buy-error",
  },
  confirmScreen: {
    launch: "#launch-game",
    goBack: "#go-back",
    confirmationParent: "#setup-confirmation",
  },
};
