export const FACTION_IDENTIFIERS = {
  desert_wolves: "desert_wolves",
  iron_corps: "iron_corps",
  liberties_vanguard: "liberties_vanguard",
  scarlet_accord: "scarlet_accord",
};

export const FACTION_IDENTIFIERS_SECONDARY = {
  steppes_raiders: "steppes_raiders",
  coronados_chosen: "coronados_chosen",
  oldburg_brigade: "oldburg_brigade",
  tanduk_conglomerate: "tanduk_conglomerate",
  serpent_scythe: "serpent_scythe",
  essex_workers_group: "essex_workers_group",
  rogue_guard: "rogue_guard",
};

export const ATTR_KEYS = {
  morale: "morale",
  initiative: "initiative",
  defense: "defense",
  offense: "offense",
  logistics: "logistics",
};

export const TRAITS = {
  stubborn: "stubborn",
  aggressive: "aggressive",
  relentless: "relentless",
  flexible: "flexible",
  disciplined: "disciplined",
  stealthy: "stealthy",
  impatient: "impatient",
  fortified: "fortified",
  cautious: "cautious",
};

export const PLAYER_ATTRIBUTE_PROFILES = {
  offensive: {
    [ATTR_KEYS.defense]: 50,
    [ATTR_KEYS.offense]: 100,
    [ATTR_KEYS.logistics]: 70,
    [ATTR_KEYS.initiative]: 90,
    [ATTR_KEYS.morale]: 80,
  },
  defensive: {
    [ATTR_KEYS.defense]: 90,
    [ATTR_KEYS.offense]: 60,
    [ATTR_KEYS.logistics]: 90,
    [ATTR_KEYS.initiative]: 60,
    [ATTR_KEYS.morale]: 90,
  },
  balanced: {
    [ATTR_KEYS.defense]: 80,
    [ATTR_KEYS.offense]: 80,
    [ATTR_KEYS.logistics]: 70,
    [ATTR_KEYS.initiative]: 80,
    [ATTR_KEYS.morale]: 80,
  },
};

export const IMAGE_PATH = {
  base: "/images/",
  green: "/images/green-portrait/",
  black: "/images/black-portrait/",
  blue: "/images/blue-portrait/",
  red: "/images/red-portrait/",
  ui: "/images/ui/",
  bg: "/images/bg/",
};

export const ANIMATIONS = {
  bounce: "animate__bounce",
  flash: "animate__flash",
  pulse: "animate__pulse",
  rubberBand: "animate__rubberBand",
  shakeX: "animate__shakeX",
  shakeY: "animate__shakeY",
  headShake: "animate__headShake",
  swing: "animate__swing",
  tada: "animate__tada",
  wobble: "animate__wobble",
  jello: "animate__jello",
  heartBeat: "animate__heartBeat",
  backInDown: "animate__backInDown",
  backInLeft: "animate__backInLeft",
  backInRight: "animate__backInRight",
  backInUp: "animate__backInUp",
  backOutDown: "animate__backOutDown",
  backOutLeft: "animate__backOutLeft",
  backOutRight: "animate__backOutRight",
  backOutUp: "animate__backOutUp",
  bounceIn: "animate__bounceIn",
  bounceInDown: "animate__bounceInDown",
  bounceInLeft: "animate__bounceInLeft",
  bounceInRight: "animate__bounceInRight",
  bounceInUp: "animate__bounceInUp",
  bounceOut: "animate__bounceOut",
  bounceOutDown: "animate__bounceOutDown",
  bounceOutLeft: "animate__bounceOutLeft",
  bounceOutRight: "animate__bounceOutRight",
  bounceOutUp: "animate__bounceOutUp",
  fadeIn: "animate__fadeIn",
  fadeInDown: "animate__fadeInDown",
  fadeInDownBig: "animate__fadeInDownBig",
  fadeInLeft: "animate__fadeInLeft",
  fadeInLeftBig: "animate__fadeInLeftBig",
  fadeInRight: "animate__fadeInRight",
  fadeInRightBig: "animate__fadeInRightBig",
  fadeInUp: "animate__fadeInUp",
  fadeInUpBig: "animate__fadeInUpBig",
  fadeInTopLeft: "animate__fadeInTopLeft",
  fadeInTopRight: "animate__fadeInTopRight",
  fadeInBottomLeft: "animate__fadeInBottomLeft",
  fadeInBottomRight: "animate__fadeInBottomRight",
  fadeOut: "animate__fadeOut",
  fadeOutDown: "animate__fadeOutDown",
  fadeOutDownBig: "animate__fadeOutDownBig",
  fadeOutLeft: "animate__fadeOutLeft",
  fadeOutLeftBig: "animate__fadeOutLeftBig",
  fadeOutRight: "animate__fadeOutRight",
  fadeOutRightBig: "animate__fadeOutRightBig",
  fadeOutUp: "animate__fadeOutUp",
  fadeOutUpBig: "animate__fadeOutUpBig",
  fadeOutTopLeft: "animate__fadeOutTopLeft",
  fadeOutTopRight: "animate__fadeOutTopRight",
  fadeOutBottomRight: "animate__fadeOutBottomRight",
  fadeOutBottomLeft: "animate__fadeOutBottomLeft",
  flip: "animate__flip",
  flipInX: "animate__flipInX",
  flipInY: "animate__flipInY",
  flipOutX: "animate__flipOutX",
  flipOutY: "animate__flipOutY",
  lightSpeedInRight: "animate__lightSpeedInRight",
  lightSpeedInLeft: "animate__lightSpeedInLeft",
  lightSpeedOutRight: "animate__lightSpeedOutRight",
  lightSpeedOutLeft: "animate__lightSpeedOutLeft",
  rotateIn: "animate__rotateIn",
  rotateInDownLeft: "animate__rotateInDownLeft",
  rotateInDownRight: "animate__rotateInDownRight",
  rotateInUpLeft: "animate__rotateInUpLeft",
  rotateInUpRight: "animate__rotateInUpRight",
  rotateOut: "animate__rotateOut",
  rotateOutDownLeft: "animate__rotateOutDownLeft",
  rotateOutDownRight: "animate__rotateOutDownRight",
  rotateOutUpLeft: "animate__rotateOutUpLeft",
  rotateOutUpRight: "animate__rotateOutUpRight",
  hinge: "animate__hinge",
  jackInTheBox: "animate__jackInTheBox",
  rollIn: "animate__rollIn",
  rollOut: "animate__rollOut",
  zoomIn: "animate__zoomIn",
  zoomInDown: "animate__zoomInDown",
  zoomInLeft: "animate__zoomInLeft",
  zoomInRight: "animate__zoomInRight",
  zoomInUp: "animate__zoomInUp",
  zoomOut: "animate__zoomOut",
  zoomOutDown: "animate__zoomOutDown",
  zoomOutLeft: "animate__zoomOutLeft",
  zoomOutRight: "animate__zoomOutRight",
  zoomOutUp: "animate__zoomOutUp",
  slideInDown: "animate__slideInDown",
  slideInLeft: "animate__slideInLeft",
  slideInRight: "animate__slideInRight",
  slideInUp: "animate__slideInUp",
  slideOutDown: "animate__slideOutDown",
  slideOutLeft: "animate__slideOutLeft",
  slideOutRight: "animate__slideOutRight",
  slideOutUp: "animate__slideOutUp",
};
