/** Trait descriptions (mechanical) and flavor text for the Game Codex. */

export type TraitCodexEntry = {
  description: string;
  flavor: string;
};

export const TRAIT_CODEX: Partial<Record<string, TraitCodexEntry>> = {
  agile: { description: "Fast reflexes and keen eyes, but fragile.", flavor: "Moves like a shadow. Doesn't take a hit well." },
  alpha_dog: { description: "Strong will and presence.", flavor: "Born to lead. Others naturally fall in behind." },
  balanced: { description: "Modest gains across all stats.", flavor: "The jack of all trades. Reliable in any role." },
  brutal: { description: "Tough and aggressive. Moderate bonuses across HP, morale, toughness.", flavor: "No subtlety. Lots of impact." },
  brawler: { description: "Aggressive close fighter. Good morale and HP, poor awareness.", flavor: "Prefers fists to sights." },
  bruiser: { description: "Heavy hitter. Extra HP and toughness.", flavor: "Built for punishment." },
  bulldog: { description: "Tenacious. High toughness, low mobility.", flavor: "Won't let go." },
  burly: { description: "Physically imposing. Strong toughness and HP, slower reflexes.", flavor: "Takes up space." },
  cold_blooded: { description: "Calm under fire. Better aim and awareness, weaker morale.", flavor: "Emotion is a liability. Efficiency is everything." },
  crusader: { description: "Zealous. High morale and toughness. Poor awareness.", flavor: "Fights for a cause." },
  cunning: { description: "Seizes opportunities. Good dex and awareness.", flavor: "Sees angles others miss." },
  cynic: { description: "Distrustful. Good awareness, weak morale and dex.", flavor: "Expects the worst. Often right." },
  defector: { description: "Turncoat. Sharp awareness but damaged and low morale.", flavor: "Switched sides. Carries baggage." },
  drifter: { description: "Unmoored. Some dex and awareness, poor toughness and HP.", flavor: "Nowhere to belong." },
  douchy: { description: "Difficult. Slight dex penalty, small awareness and morale tradeoffs.", flavor: "Nobody's favorite." },
  duelist: { description: "Precision fighter. Excellent aim and reflexes.", flavor: "Lives for the moment the crosshairs meet." },
  easy_going: { description: "Relaxed. Modest morale and toughness.", flavor: "Doesn't sweat the small stuff." },
  enforcer: { description: "Intimidating. High morale and toughness.", flavor: "Makes examples." },
  fanatic: { description: "Extremely zealous. High morale, terrible awareness.", flavor: "Blinded by belief." },
  fearless: { description: "Unshakeable nerve. Massive morale, slight awareness cost.", flavor: "Fear is for others." },
  guardian: { description: "Defensive specialist. Extra HP, toughness, awareness.", flavor: "Others advance. They hold." },
  ghost: { description: "Evasive. Good dex and awareness, fragile morale.", flavor: "Hard to pin down." },
  grunt: { description: "Foot soldier. High toughness, low dex.", flavor: "Gets it done." },
  infantry_grunt: { description: "Immune to stun and panic.", flavor: "Keeps fighting no matter what." },
  unshakeable: { description: "Immune to panic and suppression.", flavor: "Nothing breaks their focus." },
  relentless: { description: "60% higher chance to be incapacitated instead of KIA when reaching 0 HP.", flavor: "Refuses to die." },
  hardened: { description: "Battle-tested. High toughness and HP.", flavor: "Seen it all. Still standing." },
  hothead: { description: "Aggressive and tough. Terrible situational awareness.", flavor: "Charges first. Asks questions never." },
  idealist: { description: "Believes in the mission. High morale and toughness, fragile frame.", flavor: "Willing to sacrifice." },
  jaded: { description: "Observant from disillusionment. Low morale and dex.", flavor: "Stopped caring. Kept watching." },
  joker: { description: "Quick wit. Strong awareness, slight toughness penalty.", flavor: "Laughs in the face of danger." },
  kind_of_a_dick: { description: "Difficult. Penalties to dex and morale, small awareness and HP gains.", flavor: "Gets results. Loses friends." },
  loyalist: { description: "Devoted. High morale and toughness, lower dex and awareness.", flavor: "Stands by the company." },
  lunatic: { description: "Unpredictable. Extreme morale and toughness, terrible awareness.", flavor: "Unhinged. Effective." },
  marksman: { description: "Elite accuracy. Top-tier awareness and dex.", flavor: "One shot. One kill. One mistake away from gone." },
  merc: { description: "Generalist. Balanced stat gains. Trades HP for versatility.", flavor: "A job is a job. Survival is a bonus." },
  methodical: { description: "Calculated. Strong awareness and toughness. Deliberate, not swift.", flavor: "Plans every move. Never rushes." },
  model_soldier: { description: "Exemplary. Strong morale and toughness.", flavor: "Picture-perfect recruit." },
  nimble: { description: "Quick and perceptive. Fragile frame.", flavor: "Light on their feet. Light on protection." },
  obsessed: { description: "Single-minded focus. Great aim and awareness. Unstable morale.", flavor: "One thing matters. Nothing else exists." },
  opportunist: { description: "Seizes openings. Good dex and awareness.", flavor: "Strikes when the moment is right." },
  pathfinder: { description: "Scout and flanker. Good awareness and dex.", flavor: "Goes where others won't. Comes back with intel." },
  protector: { description: "Shield. High toughness, HP, and awareness.", flavor: "Takes the hit so others don't." },
  psycho: { description: "Unstable. Extreme morale, crippled awareness.", flavor: "Scary effective. Scary period." },
  reckless: { description: "Bold. Decent toughness and morale, poor awareness.", flavor: "Luck is a skill." },
  rebel: { description: "Contrarian. Strong morale, weak awareness and dex.", flavor: "Doesn't follow orders well." },
  rookie: { description: "Green. Slight morale and dex, poor awareness and HP.", flavor: "Still learning." },
  scoundrel: { description: "Cunning. Exceptional awareness, weak morale and toughness.", flavor: "Looks out for number one." },
  sentinel: { description: "Vigilant. Strong awareness, toughness, and dex.", flavor: "Eyes always open." },
  sharpshooter: { description: "Elite sniper. Outstanding awareness and dex.", flavor: "One shot. One kill." },
  skeptic: { description: "Doubtful. Slight penalties across morale, toughness, awareness.", flavor: "Trusts nothing." },
  smartass: { description: "Sarcastic. Strong awareness, weak morale.", flavor: "Mouth runs faster than feet." },
  soldier: { description: "Standard. Reliable toughness and awareness.", flavor: "Professional." },
  steady: { description: "Reliable. Good toughness and awareness. Not flashy.", flavor: "Won't surprise you. Won't disappoint either." },
  stoic: { description: "Immovable. High toughness and HP, slow reflexes.", flavor: "Ignores the pain." },
  survivor: { description: "Tough. Exceptional toughness and HP.", flavor: "Been through worse." },
  thoughtful: { description: "Observant. Enhanced awareness.", flavor: "Thinks before acting." },
  trail_blazer: { description: "Pioneer. Strong awareness and dex, decent toughness.", flavor: "Goes first." },
  trooper: { description: "Reliable infantry. Strong toughness and morale.", flavor: "Standard issue. Standard excellence." },
  unhinged: { description: "Volatile. Decent toughness and morale, poor awareness.", flavor: "One step from the edge." },
  unremarkable: { description: "No stat modifiers. Average in every way.", flavor: "Just another soldier. Exactly as intended." },
  veteran: { description: "Experienced. Good awareness, toughness, and morale.", flavor: "Been around the block." },
  war_hero: { description: "Decorated. Strong awareness, toughness, and HP.", flavor: "Proven under fire." },
  wiry: { description: "Lean. Good toughness and dex.", flavor: "Strong for their size." },
  zealot: { description: "Fanatical. High morale, fragile toughness.", flavor: "Faith over flesh." },
};
